# Generated by Django 6.1 on 2026-09-06 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0002_alter_city_options_alter_country_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="airplane",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="airplanes"),
        ),
    ]
